export const SET_CLIENT_CONFIG = 'SET_CLIENT_CONFIG';
export const SET_PAGE_LAYOUT_ALERTS = 'SET_PAGE_LAYOUT_ALERTS';
export const INCREMENT_PAGE_LAYOUT_LOADING_TASK_COUNT = 'INCREMENT_PAGE_LAYOUT_LOADING_TASK_COUNT';
export const DECREMENT_PAGE_LAYOUT_LOADING_TASK_COUNT = 'DECREMENT_PAGE_LAYOUT_LOADING_TASK_COUNT';
export const SET_PAGE_LAYOUT_HEADER = 'SET_PAGE_LAYOUT_HEADER';
export const SET_PAGE_LAYOUT_SUB_HEADER = 'SET_PAGE_LAYOUT_SUB_HEADER';
export const SET_PAGE_STATUS_CODE = 'SET_PAGE_STATUS_CODE';
